import subprocess
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch
from pdf_reduce import reduce_pdf
import synthetic_pdfs

ENGINES = synthetic_pdfs.skip_reason()

class ReductionTests(unittest.TestCase):
    def test_invalid_pdf_is_rejected(self):
        with self.assertRaises(ValueError): reduce_pdf(b'not a PDF')

    def test_failed_compression_uses_labelled_native_text_and_cleans_files(self):
        import tempfile
        def run(args, **kwargs):
            if args[0]=='pdfinfo':return subprocess.CompletedProcess(args,0,stdout=b'Pages: 1\nEncrypted: no\n')
            if args[0]=='pdftotext': Path(args[-1]).write_text('Synthetic full text');return
            raise subprocess.CalledProcessError(1,args)
        with tempfile.TemporaryDirectory() as root, patch('tempfile.tempdir',root), patch('pdf_reduce.subprocess.run',side_effect=run):
            result=reduce_pdf(b'%PDF-synthetic')
            self.assertEqual(result['kind'],'text');self.assertIn('omitted',result['text'])
            self.assertEqual(list(Path(root).iterdir()),[])

    def test_empty_or_excessive_text_does_not_become_a_silent_partial_source(self):
        def run(args, **kwargs):
            if args[0]=='pdfinfo':return subprocess.CompletedProcess(args,0,stdout=b'Pages: 1\nEncrypted: no\n')
            if args[0]=='pdftotext': Path(args[-1]).write_text('x'*200001);return
            raise subprocess.CalledProcessError(1,args)
        with patch('pdf_reduce.subprocess.run',side_effect=run), self.assertRaises(ValueError): reduce_pdf(b'%PDF-synthetic')



@unittest.skipIf(ENGINES, ENGINES)
class RealReductionTests(unittest.TestCase):
    """Ghostscript and poppler run for real, on PDFs generated by synthetic_pdfs.py (#856)."""

    def test_real_oversized_pdf_is_reduced_and_keeps_native_text(self):
        import base64
        data = synthetic_pdfs.oversized_text_pdf()
        self.assertGreater(len(data), 25 * 1024 * 1024)
        result = reduce_pdf(data)
        self.assertEqual(result['kind'], 'pdf')
        output = base64.b64decode(result['dataBase64'])
        self.assertLess(len(output), 25 * 1024 * 1024)
        with tempfile.TemporaryDirectory() as root:
            p = Path(root) / 'out.pdf'
            p.write_bytes(output)
            text = subprocess.check_output(['pdftotext', str(p), '-']).decode()
            self.assertIn('SYNTHETIC NATIVE TEXT', text)

    def test_real_encrypted_and_malformed_pdf_fail(self):
        for name, data in [('encrypted.pdf', synthetic_pdfs.encrypted_pdf()), ('malformed.pdf', synthetic_pdfs.malformed_pdf())]:
            with self.subTest(name=name), self.assertRaises(ValueError):
                reduce_pdf(data)
