"""Worker tests. The real-engine cases generate synthetic PDFs (synthetic_pdfs.py) and run
wherever tesseract, poppler and ghostscript are installed (the OCR image, and the CI job, which
installs them); elsewhere they skip and say which engine is missing."""
import os
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch
import server
import synthetic_pdfs

ENGINES = synthetic_pdfs.skip_reason()

class WorkerTests(unittest.TestCase):
    def test_subprocess_failure_is_explicit_and_temporary_files_are_removed(self):
        import tempfile
        with tempfile.TemporaryDirectory() as root:
            with patch('tempfile.tempdir', root), patch('subprocess.run', side_effect=OSError('synthetic failure')):
                out = server.process(b'fake', [1])
            self.assertIn('error', out[0])
            self.assertEqual(list(Path(root).iterdir()), [])


@unittest.skipIf(ENGINES, ENGINES)
class RealEngineTests(unittest.TestCase):
    """tesseract and poppler run for real, on PDFs generated by synthetic_pdfs.py (#856)."""

    @classmethod
    def setUpClass(cls):
        cls._directory = tempfile.TemporaryDirectory()
        cls.fixtures = synthetic_pdfs.write_all(cls._directory.name)

    @classmethod
    def tearDownClass(cls):
        cls._directory.cleanup()

    def test_real_scans_preserve_financial_rows_and_signs(self):
        for name, page in [('scanned.pdf', 1), ('mixed-page.pdf', 1), ('mixed-pages.pdf', 2)]:
            with self.subTest(name=name):
                out = server.process(self.fixtures[name].read_bytes(), [page])[0]
                self.assertNotIn('error', out)
                text = out['text']
                for value in synthetic_pdfs.ROWS:
                    self.assertIn(value, text, f'OCR output was: {text!r}')
                if name == 'mixed-page.pdf':
                    self.assertIn(synthetic_pdfs.HEADER, text, f'OCR output was: {text!r}')

    def test_a_page_with_no_text_layer_is_only_readable_by_ocr(self):
        # Guards the fixture itself: if "scanned.pdf" ever grew a text layer, the OCR test
        # above would pass without OCR doing anything.
        import subprocess
        native = subprocess.run(['pdftotext', str(self.fixtures['scanned.pdf']), '-'], capture_output=True, check=True)
        self.assertEqual(native.stdout.strip(), b'')

    def test_real_invalid_and_encrypted_documents_fail_cleanly(self):
        for name in ['malformed.pdf', 'encrypted.pdf']:
            with self.subTest(name=name):
                self.assertIn('error', server.process(self.fixtures[name].read_bytes(), [1])[0])

if __name__ == '__main__':
    unittest.main()
