"""Worker tests. The real-engine cases generate synthetic PDFs (synthetic_pdfs.py) and run
wherever tesseract, poppler and ghostscript are installed (the OCR image, and the CI job, which
installs them); elsewhere they skip and say which engine is missing."""
import os
import subprocess
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch
import server
import synthetic_pdfs

ENGINES = synthetic_pdfs.skip_reason()

class WorkerTests(unittest.TestCase):
    def test_subprocess_failure_is_explicit_and_temporary_files_are_removed(self):
        import tempfile
        with tempfile.TemporaryDirectory() as root:
            with patch('tempfile.tempdir', root), patch('subprocess.run', side_effect=OSError('synthetic failure')):
                out = server.process(b'fake', [1])
            self.assertIn('error', out[0])
            self.assertEqual(list(Path(root).iterdir()), [])


@unittest.skipIf(ENGINES, ENGINES)
class RealEngineTests(unittest.TestCase):
    """tesseract and poppler run for real, on PDFs generated by synthetic_pdfs.py (#856)."""

    @classmethod
    def setUpClass(cls):
        cls._directory = tempfile.TemporaryDirectory()
        cls.fixtures = synthetic_pdfs.write_all(cls._directory.name)

    @classmethod
    def tearDownClass(cls):
        cls._directory.cleanup()

    def test_real_scans_preserve_financial_rows_and_signs(self):
        for name, page in [('scanned.pdf', 1), ('mixed-page.pdf', 1), ('mixed-pages.pdf', 2)]:
            with self.subTest(name=name):
                out = server.process(self.fixtures[name].read_bytes(), [page])[0]
                self.assertNotIn('error', out)
                text = out['text']
                for value in synthetic_pdfs.ROWS:
                    self.assertIn(value, text, f'OCR output was: {text!r}')
                if name == 'mixed-page.pdf':
                    self.assertIn(synthetic_pdfs.HEADER, text, f'OCR output was: {text!r}')

    def test_a_page_with_no_text_layer_is_only_readable_by_ocr(self):
        # Guards the fixture itself: if "scanned.pdf" ever grew a text layer, the OCR test
        # above would pass without OCR doing anything.
        import subprocess
        native = subprocess.run(['pdftotext', str(self.fixtures['scanned.pdf']), '-'], capture_output=True, check=True)
        self.assertEqual(native.stdout.strip(), b'')

    def test_real_invalid_and_encrypted_documents_fail_cleanly(self):
        for name in ['malformed.pdf', 'encrypted.pdf']:
            with self.subTest(name=name):
                self.assertIn('error', server.process(self.fixtures[name].read_bytes(), [1])[0])

class StartupTests(unittest.TestCase):
    def run_selector(self, selector=None, features='native-ocr', feature_status=0):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            binary = root / 'noevia-ocr'
            binary.write_text(f'''#!/bin/sh
if [ "${{1-}}" = --features ]; then printf '%s\\n' '{features}'; exit {feature_status}; fi
printf 'rust-selected\\n'
''')
            binary.chmod(0o755)
            if features is None:
                binary.unlink()
            python = root / 'python'
            python.write_text('#!/bin/sh\nprintf "python-selected\\n"\n')
            python.chmod(0o755)
            script = (Path(__file__).parent / 'entrypoint.sh').read_text().replace('/usr/local/bin/noevia-ocr', str(binary))
            env = {'PATH': f'{root}:/usr/bin:/bin'}
            if selector is not None:
                env['NOEVIA_OCR_IMPL'] = selector
            return subprocess.run(['/bin/sh', '-c', script], env=env, capture_output=True, text=True, timeout=3)

    def test_unset_defaults_to_python(self):
        result = self.run_selector()
        self.assertEqual((result.returncode, result.stdout), (0, 'python-selected\n'))

    def test_explicit_python(self):
        result = self.run_selector('python')
        self.assertEqual((result.returncode, result.stdout), (0, 'python-selected\n'))

    def test_rust_executes_native_service(self):
        result = self.run_selector('rust')
        self.assertEqual((result.returncode, result.stdout), (0, 'rust-selected\n'))

    def test_unsupported_and_failed_feature_probe_refuse(self):
        for feature, status in [('', 0), ('other', 0), ('native-ocr-extra', 0), ('', 1), ('native-ocr', 1)]:
            with self.subTest(feature=feature, status=status):
                result = self.run_selector('rust', feature, status)
                self.assertNotEqual(result.returncode, 0)
                self.assertEqual(result.stdout, '')

    def test_missing_native_binary_refuses_without_python_fallback(self):
        result = self.run_selector('rust', None)
        self.assertNotEqual(result.returncode, 0)
        self.assertEqual(result.stdout, '')

    def test_invalid_selector_refuses_without_fallback(self):
        for selector in ['', 'Rust', 'node', 'rust python']:
            with self.subTest(selector=selector):
                result = self.run_selector(selector)
                self.assertNotEqual(result.returncode, 0)
                self.assertEqual(result.stdout, '')


if __name__ == '__main__':
    unittest.main()
